#!/usr/bin/env bash
# new-machine-setup.sh — certify a new machine for Price of Dawn campaign work
# Run once after cloning the repo.
# Usage: bash scripts/new-machine-setup.sh [--skip-piper] [--skip-quarto]

set -euo pipefail
REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SKIP_PIPER=0; SKIP_QUARTO=0
for arg in "$@"; do [[ "$arg" == "--skip-piper" ]] && SKIP_PIPER=1; [[ "$arg" == "--skip-quarto" ]] && SKIP_QUARTO=1; done

log() { echo "[setup] $*"; }

# ── 1. Node / npm ─────────────────────────────────────────────────────────────
if ! command -v node &>/dev/null; then
  log "Installing Node via nvm..."
  curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  export NVM_DIR="$HOME/.nvm"; source "$NVM_DIR/nvm.sh"
  nvm install --lts
else
  log "Node $(node --version) already installed."
fi

# ── 2. Claude Code CLI ────────────────────────────────────────────────────────
if ! command -v claude &>/dev/null; then
  log "Installing Claude Code..."
  npm install -g @anthropic-ai/claude-code
else
  log "Claude Code $(claude --version 2>/dev/null || echo '?') already installed."
fi

# ── 3. Ruflo / claude-flow (optional, for swarm features) ────────────────────
if ! command -v claude-flow &>/dev/null; then
  log "Initialising claude-flow (minimal)..."
  cd "$REPO_DIR" && npx @claude-flow/cli@latest init --minimal --no-interactive 2>/dev/null || true
fi

# ── 4. Quarto (builds the campaign book) ─────────────────────────────────────
if [[ "$SKIP_QUARTO" -eq 0 ]]; then
  if ! command -v quarto &>/dev/null; then
    log "Quarto not found. Download from: https://quarto.org/docs/get-started/"
    log "Or: curl -LO https://github.com/quarto-dev/quarto-cli/releases/latest/download/quarto-linux-amd64.deb && sudo dpkg -i quarto-linux-amd64.deb"
  else
    log "Quarto $(quarto --version) already installed."
  fi
fi

# ── 5. Python deps ────────────────────────────────────────────────────────────
if command -v python3 &>/dev/null; then
  log "Installing pykeepass (for credential helper)..."
  pip3 install --quiet pykeepass 2>/dev/null || pip install --quiet pykeepass 2>/dev/null || true
fi

# ── 6. Piper TTS (optional, machine-specific path) ───────────────────────────
if [[ "$SKIP_PIPER" -eq 0 ]]; then
  if [[ -z "${PIPER_ROOT:-}" ]]; then
    log "Piper not configured. Set PIPER_ROOT=/path/to/piper-sample-generator in your shell profile."
    log "  git clone https://github.com/lstein/piper-sample-generator \$PIPER_ROOT"
    log "  cd \$PIPER_ROOT && python3 -m venv .venv && source .venv/bin/activate && pip install -e ."
  else
    log "PIPER_ROOT=$PIPER_ROOT"
  fi
fi

# ── 7. API keys from KeePass ──────────────────────────────────────────────────
DB="$REPO_DIR/passwords.kdbx"
if [[ -f "$DB" ]]; then
  log "Loading API keys from passwords.kdbx (master: DndBaby100!)..."
  python3 - <<PYEOF
import sys
try:
    from pykeepass import PyKeePass
    kp = PyKeePass('$DB', password='DndBaby100!')
    keys = {
        'GROQ_API_KEY':       'GROQ_API_KEY',
        'ANTHROPIC_API_KEY':  'ANTHROPIC_API_KEY',
        'OPENROUTER_API_KEY': 'OPENROUTER_API_KEY',
        'MISTRAL_API_KEY':    'MISTRAL_API_KEY',
    }
    lines = []
    for entry_title, env_var in keys.items():
        e = kp.find_entries(title=entry_title, first=True)
        if e and e.password:
            lines.append(f'export {env_var}="{e.password}"')
    if lines:
        exports_file = '$REPO_DIR/.env.campaign'
        with open(exports_file, 'w') as f:
            f.write('# Auto-generated by new-machine-setup.sh — DO NOT COMMIT\n')
            f.write('\n'.join(lines) + '\n')
        print(f'[setup] API keys written to .env.campaign')
        print(f'[setup] Add to shell: source {exports_file}')
    else:
        print('[setup] No keys found in KeePass')
except Exception as ex:
    print(f'[setup] KeePass read failed: {ex}')
    print('[setup] Set API keys manually in your shell profile.')
PYEOF
else
  log "passwords.kdbx not found at $DB — copy from Nextcloud sync or main machine."
  log "AI APIs needed: ANTHROPIC_API_KEY, GROQ_API_KEY, OPENROUTER_API_KEY, MISTRAL_API_KEY"
fi

# ── 8. mTLS client cert (for research-ready.nl AI stack access) ──────────────
log "---"
log "To access research-ready.nl AI services (CrewAI, LiteLLM, OpenWebUI etc.):"
log "  You need the mTLS client cert from the main machine (fedora):"
log "  scp chris@<fedora>:~/Desktop/fedora.p12 ~/Desktop/campaign-client.p12"
log "  Password: Research-mTLS-2024!"
log "  Import into Firefox: Settings → Privacy → Certificates → Your Certificates → Import"
log "  Import into Chrome/Brave: Settings → Privacy → Manage certificates → Import"

# ── Done ──────────────────────────────────────────────────────────────────────
log "---"
log "Setup complete. Checklist:"
log "  [$(command -v claude &>/dev/null && echo 'x' || echo ' ')] Claude Code CLI"
log "  [$(command -v quarto &>/dev/null && echo 'x' || echo ' ')] Quarto"
log "  [$([ -f \"$REPO_DIR/.env.campaign\" ] && echo 'x' || echo ' ')] API keys (.env.campaign)"
log "  [$([ -n \"${PIPER_ROOT:-}\" ] && echo 'x' || echo ' ')] Piper TTS (PIPER_ROOT)"
log ""
log "Start working: cd $REPO_DIR && claude"
